version: '3.9'
services:
  zookeeper:
    image: bitnami/zookeeper:3
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes

  kafka:
    image: bitnami/kafka:3
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://[::1]:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://[::1]:9093
      ALLOW_PLAINTEXT_LISTENER: yes
    ports:
      - 9093:9092
    volumes:
      - kafka_data:/bitnami/kafka/data

volumes:
  kafka_data: